### ISSUE TITLE
Cryptic error message on missing width/height attributes

### ISSUE THREAD

**Issue by bannmann** [diffplug/image-grinder#6]
My SVGs (from https://game-icons.net/) don't have `width` and `height` attributes, but a `style` attribute which specifies the dimensions. This makes image-grinder fail with the following message:

```
> Task :android:convertSvgAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':android:convertSvgAssets'.
> There was a failure while executing work items
   > A failure occurred while executing com.diffplug.gradle.imagegrinder.ImageGrinderTask$RenderSvg
      > For input string: ""
```

I had to turn on stack traces and read the image-grinder source to figure out what's wrong.

Please improve this so that at least the file name is mentioned for any kind of exception. For this specific case, it would also be good to handle the error with a specific exception message like `Missing 'width' attribute`.

**Comment by nedtwigg** [comment]
PR's welcome :)

**Comment by nedtwigg** [comment]
Oops, commit referenced the wrong issue. Didn't mean to close this, but I'll keep this closed just the same since there's no specific action item.
