### ISSUE TITLE
Any documentation?

### ISSUE THREAD

**Issue by MarcinOrlowski** [diffplug/image-grinder#7]
I'd appreciate pointing to any documentation? Examples of what I can be done, some API if any etc? Or the project is dead?

**Comment by nedtwigg** [comment]
Project is not dead, just feature-complete for our internal purposes. Documentation, examples, and javadoc is all in the README, there was one broken link though which I just fixed.

![image](https://user-images.githubusercontent.com/2924992/130360945-fd537933-713e-4e09-9159-92c211f8c075.png)

![image](https://user-images.githubusercontent.com/2924992/130360915-f974509c-6c3e-453c-b42b-0abc1a9055ae.png)

**Comment by MarcinOrlowski** [comment]
Please reopen. I am flagging, that as new user I am having problems how to use this plugin. Is it docs' fault or mine, I do not know, I will post the case I want to convert to use via this plugin as currently I am using Inkscape driven by external bash script.

**Comment by nedtwigg** [comment]
Feel free to keep posting info :)
